name          'elibus-oracle_dbfs'
version       '0.1.1'
source        'https://github.com/elibus/puppet-oracle_dbs'
author        'Marco Tizzoni'
license       'Apache 2.0'
summary       'Configure Oracle DBFS'
description   ''
project_page  'https://github.com/elibus/puppet-oracle_dbs'

dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/concat'
